[workspace]
members = [
    "rsget_lib",
    "rsget_cli",
    "stream_lib",
]
resolver = "3"
package.edition = "2024"

[workspace.dependencies]
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tokio = { version = "1.52.3", default-features = false }
hls_m3u8 = "0.7.0"
reqwest = { version = "0.13.3", default-features = false }
futures-util = "0.3.32"
stream_lib = { version = "0.6", path = "./stream_lib", default-features = false }
rsget_lib = { version = "0.3", path = "./rsget_lib" }

[profile.release]
panic = "abort"
lto = true
