[package]
name = "rsget_lib"
version = "0.1.0"
authors = ["Valdemar Erk <valdemar@erk.io>"]

[dependencies]
log = "0.4.1"
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1.0"
futures = "0.1.21"
hyper = "0.12" #{ git = "https://github.com/hyperium/hyper" }
hyper-tls = "0.2" #{ git = "https://github.com/hyperium/hyper-tls" } #"0.1.3"
http = "0.1"
tokio = "0.1"
tokio-fs = "0.1.0"
tokio-core = "0.1"
indicatif = "0.9.0"
chrono = "0.4"
md5 = "0.3.7"
url = "1.7.0"
hls_m3u8 = "0.1.1"