[package]
name = "rsget_lib"
version = "0.1.0"
authors = ["Valdemar Erk <valdemar@erk.io>"]

[dependencies]
log = "0.4"
reqwest = "0.8.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "0.2"
futures = "0.1"
hyper = "0.11.18"
tokio-core = "0.1"
indicatif = "0.9.0"
chrono = "0.4"
lazy_static = "1.0"