[package]
name = "rsget_cli"
version = "0.1.0"
authors = ["Valdemar Erk <valdemar@erk.io>"]

[dependencies]
rsget_lib = { path = "../rsget_lib" }
clap = "2.29.4"
log = "0.4.0"
env_logger = "0.5.3"
tokio-core = "0.1"

[[bin]]
name = "rsget"
path = "src/main.rs"
