[package]
name = "rsget"
version = "0.1.5"
authors = ["Valdemar Erk <valdemar@erk.io>"]
description = "Tool to get information about and download livestreams"
license = "ISC"
edition.workspace = true
documentation = "https://docs.rs/rsget"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/rsget_cli"

[dependencies]
rsget_lib.workspace = true
stream_lib.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4.5.60", features = ["derive"] }
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "io-util", "io-std"] }
reqwest = { workspace = true, default-features = false }
indicatif = "0.18.4"
futures-util.workspace = true

[features]
# Default to rustls so we don't pull in openssl
default = ["rustls"]
rustls = [
  "reqwest/rustls",
]
native-tls = [
  "reqwest/native-tls",
]

[[bin]]
name = "rsget"
path = "src/main.rs"
