[package]
name = "rsget_cli"
version = "0.1.1"
authors = ["Valdemar Erk <valdemar@erk.io>"]

[dependencies]
rsget_lib = { path = "../rsget_lib" }
clap = "2.32.0"
log = "0.4"
#pretty_env_logger = "0.2"
flexi_logger = "0.9"
hyper = "0.12"
hyper-tls = "0.3"

[[bin]]
name = "rsget"
path = "src/main.rs"
