[package]
name = "rsget"
version = "0.1.4"
authors = ["Valdemar Erk <valdemar@erk.io>"]
description = "Tool to get information about and download livestreams"
license = "ISC"
edition = "2018"
documentation = "https://docs.rs/rsget"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/rsget_cli"

[dependencies]
rsget_lib = { path = "../rsget_lib" }
clap = "^2.32.0"
log = "^0.4"
flexi_logger = "^0.9"

[[bin]]
name = "rsget"
path = "src/main.rs"
