[package]
name = "stream_lib"
version = "0.6.0"
authors = ["Valdemar Erk <cargo@erk.dev>"]
description = "Tool to download differnt types of streams"
license = "ISC"
edition.workspace = true
documentation = "https://docs.rs/stream_lib"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/stream_lib"

[dependencies]
hls_m3u8.workspace = true
reqwest = { workspace = true, default-features = false, features = ["stream"] }
tracing.workspace = true
url = "2.5.8"
futures-util.workspace = true
tokio = { workspace = true, default-features = false, features = ["rt", "sync", "time"] }
patricia_tree = "0.10.1"
futures-core = "0.3.32"
bytes = "1.11.1"

[dev-dependencies]
tracing-subscriber.workspace = true
tokio = { workspace = true, default-features = false, features = ["fs", "rt", "sync", "time", "macros"] }

[features]
# Default to rustls so we don't pull in openssl
default = ["rustls"]
rustls = [
  "reqwest/rustls",
]
native-tls = [
  "reqwest/native-tls",
]
