[package]
name = "stream_lib"
version = "0.3.0"
authors = ["Valdemar Erk <v@erk.io>"]
description = "Tool to download differnt types of streams"
license = "ISC"
edition = "2018"
documentation = "https://docs.rs/stream_lib"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/stream_lib"

[dependencies]
hls_m3u8 = "0.3"
reqwest = { version = "0.10.0", features = ["stream"] }
log = "^0.4"
url = "2"
futures-util = "0.3.1"
tokio = { version = "0.2", features = ["full"] }

[dependencies.indicatif]
optional = true
version = "0.15"

[features]
default = []
spinner = ["indicatif"]
