[package]
name = "stream_lib"
version = "0.3.0"
authors = ["Valdemar Erk <v@erk.io>"]
description = "Tool to download differnt types of streams"
license = "ISC"
edition = "2018"
documentation = "https://docs.rs/stream_lib"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/stream_lib"

[dependencies]
hls_m3u8 = "0.4"
reqwest = { version = "0.11.0", features = ["stream"] }
log = "^0.4"
url = "2"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
patricia_tree = "0.3.0"

[dependencies.indicatif]
optional = true
version = "0.15"

[features]
default = []
spinner = ["indicatif"]
