[package]
name = "stream_lib"
version = "0.1.0"
authors = ["Valdemar Erk <v@erk.io>"]
description = "Tool to download differnt types of streams"
license = "ISC"
edition = "2018"
documentation = "https://docs.rs/stream_lib"
homepage = "https://github.com/Erk-/rsget"
repository = "https://github.com/Erk-/rsget/tree/master/stream_lib"

[dependencies]
hls_m3u8 = "^0.1.3"
reqwest = "^0.9"
indicatif = "0.11"
parking_lot = "^0.7"
log = "^0.4"
url = "^1.7"