[package]
name = "stream-tool"
version = "0.1.0"
authors = ["Valdemar Erk <v@erk.io>"]
license = "ISC"
edition = "2018"

[dependencies]
hls_m3u8 = "^0.1.3"
reqwest = "^0.9"
indicatif = "0.10.3"
parking_lot = "^0.7"
log = "^0.4"
url = "^1.7"